// Seed data for the prototype service catalog. Mirrors the developer repo's
// mock-service-catalog.json, but normalized to the UI-facing types: durations
// are stored as minutes (not display strings) and every service carries the
// `variants` / `extraTimes` / `isActive` fields the components expect.
//
// This is the only data source for the Service menu + Categories screens in
// this design/prototype repo — there is no API. All mutations happen in
// local React state (see store.tsx).

import type { Service, ServiceCategory } from "./types"

/** Lightweight team-member shape — the only fields the catalog screens read. */
export type TeamMember = {
  id: string
  name: string
  title?: string
}

export const seedCategories: ServiceCategory[] = [
  // System-managed top-level categories (hidden from the merchant-facing list,
  // used as parents / for resolving display names).
  {
    id: "admin-1",
    name: "Grooming",
    color: "purple",
    description: "Bathing, haircuts, nail trims, and coat care",
    order: 0,
    parentId: null,
    isSystemManaged: true,
    slug: "grooming",
    icon: "scissors",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-2",
    name: "Veterinary",
    color: "blue",
    description: "Health check-ups, vaccinations, and medical care",
    order: 1,
    parentId: null,
    isSystemManaged: true,
    slug: "veterinary",
    icon: "stethoscope",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-3",
    name: "Boarding",
    color: "teal",
    description: "Overnight and extended stay accommodation",
    order: 2,
    parentId: null,
    isSystemManaged: true,
    slug: "boarding",
    icon: "home",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-4",
    name: "Daycare",
    color: "yellow",
    description: "Daytime supervision and play activities",
    order: 3,
    parentId: null,
    isSystemManaged: true,
    slug: "daycare",
    icon: "sun",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-5",
    name: "Training",
    color: "orange",
    description: "Obedience, behaviour, and skill training",
    order: 4,
    parentId: null,
    isSystemManaged: true,
    slug: "training",
    icon: "graduation-cap",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-6",
    name: "Wellness",
    color: "green",
    description: "Spa treatments, massage, and preventive care",
    order: 5,
    parentId: null,
    isSystemManaged: true,
    slug: "wellness",
    icon: "heart",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-7",
    name: "Retail",
    color: "pink",
    description: "Products, accessories, and merchandise",
    order: 6,
    parentId: null,
    isSystemManaged: true,
    slug: "retail",
    icon: "shopping-bag",
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "admin-8",
    name: "Transport",
    color: "red",
    description: "Pick-up, drop-off, and mobile visit services",
    order: 7,
    parentId: null,
    isSystemManaged: true,
    slug: "transport",
    icon: "truck",
    isActive: true,
    servicesCount: 0,
  },
  // Merchant-created categories (shown in the Categories table + Service menu).
  {
    id: "cat-1",
    name: "Color treatments",
    color: "purple",
    description: "Hair coloring and treatment services",
    order: 0,
    parentId: "admin-1",
    isSystemManaged: false,
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "cat-2",
    name: "Hair & styling",
    color: "blue",
    description: "Haircuts, blowouts, and styling services",
    order: 1,
    parentId: "admin-1",
    isSystemManaged: false,
    isActive: true,
    servicesCount: 0,
  },
  {
    id: "cat-3",
    name: "Nail care",
    color: "pink",
    description: "Manicure and pedicure services",
    order: 2,
    parentId: "admin-1",
    isSystemManaged: false,
    isActive: true,
    servicesCount: 0,
  },
]

export const seedServices: Service[] = [
  {
    id: "svc-1",
    name: "Hair Color",
    categoryId: "cat-1",
    categoryName: "Color treatments",
    description: "Full head hair coloring",
    priceType: "Fixed",
    price: 57,
    duration: 75,
    order: 0,
    teamMemberIds: ["tm-1", "tm-2"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-2",
    name: "Haircut",
    categoryId: "cat-1",
    categoryName: "Color treatments",
    description: "Precision haircut",
    priceType: "Fixed",
    price: 40,
    duration: 45,
    order: 1,
    teamMemberIds: ["tm-1", "tm-2", "tm-3"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-3",
    name: "Brazilian Blowout",
    categoryId: "cat-2",
    categoryName: "Hair & styling",
    description: "Smoothing treatment",
    priceType: "Fixed",
    price: 100,
    duration: 60,
    order: 0,
    teamMemberIds: ["tm-2"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-4",
    name: "Blow Dry",
    categoryId: "cat-2",
    categoryName: "Hair & styling",
    description: "Professional blowout",
    priceType: "Fixed",
    price: 35,
    duration: 35,
    order: 1,
    teamMemberIds: ["tm-1", "tm-3"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-5",
    name: "Deep Conditioning",
    categoryId: "cat-2",
    categoryName: "Hair & styling",
    description: "Intensive moisture treatment",
    priceType: "Fixed",
    price: 65,
    duration: 60,
    order: 2,
    teamMemberIds: ["tm-2", "tm-3"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-6",
    name: "Classic Manicure",
    categoryId: "cat-3",
    categoryName: "Nail care",
    description: "Nail shaping, cuticle care and polish",
    priceType: "Fixed",
    price: 25,
    duration: 30,
    order: 0,
    teamMemberIds: ["tm-3"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
  {
    id: "svc-7",
    name: "Gel Manicure",
    categoryId: "cat-3",
    categoryName: "Nail care",
    description: "Long-lasting gel polish application",
    priceType: "Fixed",
    price: 45,
    duration: 45,
    order: 1,
    teamMemberIds: ["tm-3"],
    isActive: true,
    variants: [],
    extraTimes: [],
  },
]

export const seedTeamMembers: TeamMember[] = [
  { id: "tm-1", name: "Sarah Johnson" },
  { id: "tm-2", name: "James Carter", title: "Cashier" },
  { id: "tm-3", name: "Emily Rivera" },
]
