// The 26 MVP reports (Maaz's "Cami Reports" sheet), each defined as config the
// shared view templates render. Columns come from the Fresha reference, adapted
// to Cami's domain (AED, CamiPay/NeoPay/Cash, Pet Name in Client reports).
//
// held: parked until scope is confirmed with Michelle/Maaz — kept here so
// un-holding is a one-line change. Filtered out of the live index.

import type { ReportCategory, ReportDef } from "./types"

export const CATEGORY_ORDER: ReportCategory[] = [
  "dashboards",
  "sales",
  "finance",
  "appointments",
  "team",
  "clients",
  "inventory",
]

export const CATEGORY_LABELS: Record<ReportCategory, string> = {
  dashboards: "Dashboards",
  sales: "Sales",
  finance: "Finance",
  appointments: "Appointments",
  team: "Team",
  clients: "Clients",
  inventory: "Inventory",
}

export const REPORTS: ReportDef[] = [
  // ─── Dashboards (feature-flagged — future add-on pricing) ──────────────────
  {
    id: "performance-dashboard",
    category: "dashboards",
    name: "Performance dashboard",
    description: "Dashboard of your business performance.",
    template: "dashboard",
    dateControl: "range-compare",
    premium: true,
    featureFlagged: true,
  },
  {
    id: "performance-summary",
    category: "sales",
    name: "Performance summary",
    description: "Overview of business performance by team or location.",
    template: "dashboard",
    dateControl: "range-compare",
    premium: true,
    featureFlagged: true,
    filters: ["location", "teamMember", "channel"],
  },
  {
    id: "performance-over-time",
    category: "sales",
    name: "Performance over time",
    description: "View of key business metrics by location or team member over time.",
    template: "dashboard",
    dateControl: "range-compare",
    premium: true,
    featureFlagged: true,
    filters: ["location", "teamMember"],
  },

  // ─── Sales ─────────────────────────────────────────────────────────────────
  {
    id: "sales-summary",
    category: "sales",
    name: "Sales summary",
    description: "Sales quantities and value, excluding tips and gift card sales.",
    template: "table",
    dateControl: "range",
    // Group by Product gives Aziz's "sales by item" (DSG-43).
    groupBy: { label: "Type", options: ["Type", "Item", "Team member", "Location"] },
    totalRow: true,
    columns: [
      { key: "type", label: "Type", kind: "text" },
      { key: "salesQty", label: "Sales qty", kind: "number" },
      { key: "itemsSold", label: "Items sold", kind: "number" },
      { key: "grossSales", label: "Gross sales", kind: "money" },
      { key: "totalDiscounts", label: "Total discounts", kind: "money" },
      { key: "refunds", label: "Refunds", kind: "money" },
      { key: "netSales", label: "Net sales", kind: "money" },
      { key: "taxes", label: "Taxes", kind: "money" },
      { key: "totalSales", label: "Total sales", kind: "money", emphasis: true },
    ],
    filters: ["location", "type", "teamMember", "channel", "paymentMethod"],
  },
  {
    id: "sales-log-detail",
    category: "sales",
    name: "Sales log detail",
    description: "In-depth view into each sale transaction.",
    template: "table",
    dateControl: "range",
    totalRow: true,
    columns: [
      { key: "date", label: "Date", kind: "datetime" },
      { key: "saleNo", label: "Sale no.", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "type", label: "Type", kind: "text" },
      { key: "item", label: "Item", kind: "text" },
      { key: "category", label: "Category", kind: "text" },
      { key: "client", label: "Client", kind: "link" },
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "channel", label: "Channel", kind: "text" },
      { key: "grossSales", label: "Gross sales", kind: "money" },
      { key: "itemDiscounts", label: "Item discounts", kind: "money" },
      { key: "cartDiscounts", label: "Cart discounts", kind: "money" },
      { key: "totalDiscounts", label: "Total discounts", kind: "money" },
      { key: "refunds", label: "Refunds", kind: "money" },
      { key: "netSales", label: "Net sales", kind: "money" },
      { key: "taxesOnNetSales", label: "Taxes on net sales", kind: "money" },
      { key: "totalSales", label: "Total sales", kind: "money", emphasis: true },
    ],
    filters: ["location", "type", "teamMember", "channel"],
  },
  {
    id: "discount-summary",
    category: "sales",
    name: "Discount summary",
    description: "Overview of discounts granted and their impact on sales.",
    template: "table",
    dateControl: "range",
    groupBy: { label: "Discount category", options: ["Discount category", "Discount type"] },
    columns: [
      { key: "discountCategory", label: "Discount category", kind: "text" },
      { key: "itemsDiscounted", label: "Items discounted", kind: "number" },
      { key: "grossSales", label: "Gross sales", kind: "money" },
      { key: "itemDiscounts", label: "Item discounts", kind: "money" },
      { key: "cartDiscounts", label: "Cart discounts", kind: "money" },
      { key: "totalDiscounts", label: "Total discounts", kind: "money" },
      { key: "totalDiscountPct", label: "Total discount %", kind: "percent" },
    ],
    filters: ["location", "discountCategory"],
  },

  // ─── Finance ─────────────────────────────────────────────────────────────
  {
    id: "finance-summary",
    category: "finance",
    name: "Finance summary",
    description: "High-level summary of sales, payments and liabilities.",
    template: "detailed-table",
    dateControl: "range-granularity",
    filters: ["location"],
  },
  {
    id: "taxes-summary",
    category: "finance",
    name: "Taxes summary",
    description: "Summary of all tax-related transactions.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "taxType", label: "Tax type", kind: "text" },
      { key: "location", label: "Location", kind: "text" },
      { key: "taxRate", label: "Tax rate", kind: "percent" },
      { key: "itemsSold", label: "Items sold", kind: "number" },
      { key: "taxesOnNetSales", label: "Taxes on net sales", kind: "money" },
      { key: "taxOnServiceCharges", label: "Tax on service charges", kind: "money" },
      { key: "totalTax", label: "Total tax", kind: "money", emphasis: true },
    ],
    filters: ["location"],
  },
  {
    id: "payments-summary",
    category: "finance",
    name: "Payments summary",
    description: "Payments split by payment methods.",
    template: "table",
    dateControl: "range",
    totalRow: true,
    columns: [
      { key: "paymentMethod", label: "Payment method", kind: "text" },
      { key: "noOfPayments", label: "No. of payments", kind: "number" },
      { key: "paymentAmount", label: "Payment amount", kind: "money" },
      { key: "noOfRefunds", label: "No. of refunds", kind: "number" },
      { key: "refunds", label: "Refunds", kind: "money" },
      { key: "netPayments", label: "Net payments", kind: "money", emphasis: true },
    ],
    filters: ["location", "paymentMethod"],
  },
  {
    // Maaz's sheet labels this "Detailed Table", but the Fresha view is a flat
    // per-transaction table — so it uses the Table template.
    id: "payment-transactions",
    category: "finance",
    name: "Payment transactions",
    description: "Detailed view of all payment transactions.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "paymentDate", label: "Payment date", kind: "datetime" },
      { key: "paymentNo", label: "Payment no.", kind: "text" },
      { key: "saleDate", label: "Sale date", kind: "datetime" },
      { key: "saleNo", label: "Sale no.", kind: "link" },
      { key: "apptRef", label: "Appt. ref.", kind: "link" },
      { key: "client", label: "Client", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "transactionType", label: "Transaction type", kind: "text" },
      { key: "paymentMethod", label: "Payment method", kind: "text" },
      { key: "paymentAmount", label: "Payment amount", kind: "money", emphasis: true },
    ],
    filters: ["location", "paymentMethod", "teamMember", "type"],
  },

  // ─── Appointments ──────────────────────────────────────────────────────────
  {
    id: "appointments-summary",
    category: "appointments",
    name: "Appointments summary",
    description:
      "General overview of appointment trends and patterns, including cancellations and no-shows.",
    template: "table",
    dateControl: "range",
    groupBy: { label: "Location", options: ["Location", "Team member", "Service"] },
    totalRow: true,
    // Each summary row drills into the Appointments list, filtered to the
    // clicked entity for whichever dimension is grouped (Fresha parity).
    drillThrough: {
      report: "appointments-list",
      paramByDimension: { Location: "location", "Team member": "teamMember", Service: "service" },
    },
    columns: [
      { key: "location", label: "Location", kind: "text" },
      { key: "appointments", label: "Appointments", kind: "number" },
      { key: "services", label: "Services", kind: "number" },
      { key: "pctRequested", label: "% requested", kind: "percent" },
      { key: "totalApptValue", label: "Total appt. value", kind: "money" },
      { key: "avgApptValue", label: "Average appt. value", kind: "money" },
      { key: "pctOnline", label: "% online", kind: "percent" },
      { key: "pctCancelled", label: "% cancelled", kind: "percent" },
      { key: "pctNoShow", label: "% no show", kind: "percent" },
      { key: "totalClients", label: "Total clients", kind: "number" },
      { key: "newClients", label: "New clients", kind: "number" },
      { key: "pctNewClients", label: "% new clients", kind: "percent" },
      { key: "pctReturningClients", label: "% returning clients", kind: "percent" },
    ],
    filters: ["location", "teamMember", "channel", "status"],
  },
  {
    id: "appointments-list",
    category: "appointments",
    name: "Appointments list",
    description: "Full list of scheduled appointments.",
    template: "table",
    dateControl: "range",
    totalRow: true,
    columns: [
      { key: "apptRef", label: "Appt. ref.", kind: "link" },
      { key: "client", label: "Client", kind: "link" },
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "resource", label: "Resource", kind: "text" },
      { key: "status", label: "Status", kind: "status" },
      { key: "createdDate", label: "Created date", kind: "datetime" },
      { key: "scheduledDate", label: "Scheduled date", kind: "datetime" },
      { key: "cancelledDate", label: "Cancelled date", kind: "datetime" },
      { key: "category", label: "Category", kind: "text" },
      { key: "service", label: "Service", kind: "text" },
      { key: "duration", label: "Duration", kind: "duration" },
      { key: "apptSlot", label: "Appt. slot", kind: "text" },
      { key: "createdBy", label: "Created by", kind: "link" },
      { key: "cancelledBy", label: "Cancelled by", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "netSales", label: "Net sales", kind: "money" },
      { key: "cancellationReason", label: "Cancellation reason", kind: "text" },
      { key: "feesCharged", label: "Fees charged", kind: "money" },
      { key: "prepayments", label: "Prepayments", kind: "money" },
    ],
    filters: ["location", "teamMember", "status", "category", "channel"],
  },
  {
    id: "cancellations-no-show-summary",
    category: "appointments",
    name: "Appointments cancellations & no-show summary",
    description: "Insight into appointment cancellations and no-shows.",
    template: "table",
    dateControl: "range",
    totalRow: true,
    columns: [
      { key: "reason", label: "Reason", kind: "text" },
      { key: "noOfAppointments", label: "No. of appointments", kind: "number" },
      { key: "value", label: "Value", kind: "money" },
      { key: "feesCharged", label: "Fees charged", kind: "money" },
    ],
    filters: ["location", "teamMember"],
  },

  // ─── Team ────────────────────────────────────────────────────────────────
  {
    id: "tips-summary",
    category: "team",
    name: "Tips summary",
    description: "Analysis of gratuity income.",
    template: "table",
    dateControl: "range",
    groupBy: { label: "Team member", options: ["Team member", "Location"] },
    totalRow: true,
    columns: [
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "tipsCollected", label: "Tips collected", kind: "money" },
      { key: "tipsRefunded", label: "Tips refunded", kind: "money" },
      { key: "totalTips", label: "Total tips", kind: "money", emphasis: true },
    ],
    filters: ["location", "teamMember"],
  },
  {
    id: "tips-detail",
    category: "team",
    name: "Tips detail",
    description: "Comprehensive breakdown of all tips received.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "saleNo", label: "Sale no.", kind: "link" },
      { key: "saleDate", label: "Sale date", kind: "datetime" },
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "client", label: "Client", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "transactionType", label: "Transaction type", kind: "text" },
      { key: "channel", label: "Channel", kind: "text" },
      { key: "paymentMethod", label: "Payment method", kind: "text" },
      { key: "tipsCollected", label: "Tips collected", kind: "money", emphasis: true },
    ],
    filters: ["location", "teamMember", "channel", "paymentMethod"],
  },
  // NOTE: Commission activity + Commission summary are OUT of scope (Michelle:
  // PRO-703 §7 wins over Maaz's sheet). Intentionally omitted.
  {
    id: "working-hours-summary",
    category: "team",
    name: "Working hours summary",
    description: "Overview of operational hours and productivity.",
    template: "table",
    dateControl: "range",
    groupBy: { label: "Team member", options: ["Team member", "Location"] },
    totalRow: true,
    columns: [
      { key: "teamMember", label: "Team member", kind: "link" },
      { key: "scheduled", label: "Scheduled", kind: "duration" },
      { key: "timeOff", label: "Time off", kind: "duration" },
      { key: "blocked", label: "Blocked", kind: "duration" },
      { key: "available", label: "Available", kind: "duration" },
      { key: "booked", label: "Booked", kind: "duration" },
      { key: "unbooked", label: "Unbooked", kind: "duration" },
      {
        key: "pctOccupancy",
        label: "% Occupancy",
        kind: "percent",
        totalFrom: { numerator: "booked", denominator: "available" },
      },
    ],
    filters: ["location", "teamMember"],
  },

  // ─── Clients ─────────────────────────────────────────────────────────────
  {
    id: "client-summary",
    category: "clients",
    name: "Client summary",
    description:
      "Overview of new, returning and walk-in clients with appointments in the chosen timeframe.",
    template: "table",
    dateControl: "range",
    groupBy: { label: "Location", options: ["Location", "Team member"] },
    totalRow: true,
    columns: [
      { key: "location", label: "Location", kind: "text" },
      { key: "totalClients", label: "Total clients", kind: "number" },
      { key: "newClients", label: "New clients", kind: "number" },
      { key: "pctNew", label: "% new", kind: "percent" },
      { key: "newClientsAtLocation", label: "New clients at location", kind: "number" },
      { key: "pctNewAtLocation", label: "% new clients at location", kind: "percent" },
      { key: "returningClients", label: "Returning clients", kind: "number" },
      { key: "pctReturning", label: "% returning", kind: "percent" },
      { key: "returningClientsAtLocation", label: "Returning clients at location", kind: "number" },
      { key: "pctReturningAtLocation", label: "% returning clients at location", kind: "percent" },
      { key: "walkInClients", label: "Walk-in clients", kind: "number" },
      { key: "pctWalkIns", label: "% walk-ins", kind: "percent" },
      { key: "rebooked", label: "Rebooked", kind: "number" },
      { key: "pctRebooked", label: "% rebooked", kind: "percent" },
      { key: "rebookedClientsAtLocation", label: "Rebooked clients at location", kind: "number" },
      { key: "pctRebookedAtLocation", label: "% rebooked clients at location", kind: "percent" },
    ],
    filters: ["location", "clientRetention"],
  },
  {
    // Client insights is merged in here (Michelle: insights = a filtered view of
    // this list), so Client list carries the richer per-client columns.
    id: "client-list",
    category: "clients",
    name: "Client list",
    description: "Comprehensive list of all active clients.",
    template: "table",
    dateControl: "range",
    hasPetColumn: true,
    columns: [
      { key: "client", label: "Client", kind: "link" },
      { key: "pet", label: "Pet", kind: "link" },
      { key: "gender", label: "Gender", kind: "text" },
      { key: "age", label: "Age", kind: "number" },
      { key: "mobile", label: "Mobile number", kind: "text" },
      { key: "email", label: "Email", kind: "text" },
      { key: "rebooked", label: "Rebooked", kind: "boolean" },
      { key: "clientSource", label: "Client source", kind: "text" },
      { key: "referredBy", label: "Referred by", kind: "text" },
      { key: "addedOn", label: "Added on", kind: "date" },
      { key: "firstAppt", label: "First appt.", kind: "date" },
      { key: "lastAppt", label: "Last appt.", kind: "date" },
      { key: "totalAppts", label: "Total appts", kind: "number" },
      { key: "totalApptValue", label: "Total appt. value", kind: "money" },
      { key: "reviews", label: "Reviews", kind: "text" },
    ],
    filters: ["clientGender", "clientRetention"],
  },

  // ─── Inventory ─────────────────────────────────────────────────────────────
  {
    id: "stock-on-hand",
    category: "inventory",
    name: "Stock on hand",
    description: "Current status and quantity of stock items.",
    template: "table",
    dateControl: "single-date",
    totalRow: true,
    columns: [
      { key: "brand", label: "Brand", kind: "text" },
      { key: "primarySku", label: "Primary SKU", kind: "text" },
      { key: "product", label: "Product", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "stockOnHand", label: "Stock on hand", kind: "number" },
      { key: "totalCost", label: "Total cost", kind: "money" },
      { key: "avgCost", label: "Avg. cost", kind: "money" },
      { key: "retailPrice", label: "Retail price", kind: "money" },
      { key: "retailValue", label: "Retail value", kind: "money" },
      { key: "supplyPrice", label: "Supply price", kind: "money" },
      { key: "supplyValue", label: "Supply value", kind: "money" },
      { key: "pctMargin", label: "% margin", kind: "percent" },
      { key: "lowStockLevel", label: "Low stock level", kind: "number" },
      { key: "reorderQty", label: "Reorder qty", kind: "number" },
    ],
    filters: ["location", "brand", "supplier"],
  },
  {
    id: "stock-movement-summary",
    category: "inventory",
    name: "Stock movement summary",
    description: "Summary of stock inflow and outflow.",
    template: "table",
    dateControl: "range",
    totalRow: true,
    columns: [
      { key: "brand", label: "Brand", kind: "text" },
      { key: "primarySku", label: "Primary SKU", kind: "text" },
      { key: "product", label: "Product", kind: "link" },
      { key: "startStock", label: "Start stock", kind: "number" },
      { key: "received", label: "Received", kind: "number" },
      { key: "sold", label: "Sold", kind: "number" },
      { key: "adjusted", label: "Adjusted", kind: "number" },
      { key: "endStock", label: "End stock", kind: "number" },
      { key: "ordered", label: "Ordered stock", kind: "number" },
    ],
    filters: ["location", "brand"],
  },
  {
    id: "stock-movement-log",
    category: "inventory",
    name: "Stock movement log",
    description: "Detailed record of all stock movements.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "date", label: "Date", kind: "datetime" },
      { key: "brand", label: "Brand", kind: "text" },
      { key: "primarySku", label: "Primary SKU", kind: "text" },
      { key: "product", label: "Product", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "adjReason", label: "Adj. reason", kind: "text" },
      { key: "adjRef", label: "Adj. ref.", kind: "link" },
      { key: "qty", label: "Qty", kind: "number" },
      { key: "cost", label: "Cost", kind: "money" },
      { key: "avgCost", label: "Avg. cost", kind: "money" },
    ],
    filters: ["location", "brand"],
  },
  {
    id: "product-list",
    category: "inventory",
    name: "Product list",
    description: "Comprehensive list of all products.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "primarySku", label: "Primary SKU", kind: "text" },
      { key: "product", label: "Product", kind: "link" },
      { key: "category", label: "Category", kind: "text" },
      { key: "brand", label: "Brand", kind: "text" },
      { key: "barcode", label: "Barcode", kind: "text" },
      { key: "supplier", label: "Supplier", kind: "text" },
      { key: "hasDescription", label: "Has description", kind: "boolean" },
      { key: "hasImage", label: "Has image", kind: "boolean" },
      { key: "units", label: "Units", kind: "number" },
      { key: "uom", label: "UoM", kind: "text" },
      { key: "retailPrice", label: "Retail price", kind: "money" },
    ],
    filters: ["brand", "supplier", "category"],
  },
  {
    id: "ordered-stock",
    category: "inventory",
    name: "Ordered stock",
    description: "Detailed record of all stock orders.",
    template: "table",
    dateControl: "range",
    columns: [
      { key: "ordered", label: "Ordered", kind: "date" },
      { key: "expected", label: "Expected", kind: "date" },
      { key: "received", label: "Received", kind: "date" },
      { key: "reference", label: "Reference", kind: "text" },
      { key: "product", label: "Product", kind: "link" },
      { key: "location", label: "Location", kind: "text" },
      { key: "supplier", label: "Supplier", kind: "text" },
      { key: "orderQty", label: "Order qty", kind: "number" },
      { key: "receivedQty", label: "Received qty", kind: "number" },
      { key: "cancelledQty", label: "Cancelled qty.", kind: "number" },
      { key: "pendingStock", label: "Pending stock", kind: "number" },
      { key: "totalCost", label: "Total cost", kind: "money" },
      { key: "avgUnitCost", label: "Avg. unit cost", kind: "money" },
      { key: "status", label: "Status", kind: "status" },
    ],
    filters: ["location", "supplier"],
  },
]

/** All reports whose scope is confirmed (excludes `held`). */
export const LIVE_REPORTS = REPORTS.filter((r) => !r.held)

export function getReport(id: string): ReportDef | undefined {
  return REPORTS.find((r) => r.id === id)
}

export function liveReportsByCategory(category: ReportCategory): ReportDef[] {
  return LIVE_REPORTS.filter((r) => r.category === category)
}

/** Categories that currently have at least one live report (for index tabs). */
export function liveCategories(): ReportCategory[] {
  return CATEGORY_ORDER.filter((c) => LIVE_REPORTS.some((r) => r.category === c))
}
