#!/usr/bin/env bash
# Pull designated Slite notes into context/slite/ so they load at session start.
#
# Runs on SessionStart. Never blocks a session: every failure path exits 0 and
# leaves the previous cache in place, so a Slite outage or an expired token
# degrades to stale context rather than no context.
#
# Requires SLITE_API_KEY in the environment. Create a token at
# Slite > Settings > API, then export it from your shell profile:
#   export SLITE_API_KEY="..."
#
# What to pull is listed in .claude/slite-notes.tsv, one note per line:
#   <noteId><TAB><output-filename.md><TAB><human label>
#
# RULE: only pull notes with NO repo counterpart. The knowledge docs (01-06)
# and context/*.md are authored in this repo and mirrored OUT to Slite. Pulling
# them back in would load both copies into context and make it ambiguous which
# one wins.

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LIST="$ROOT/.claude/slite-notes.tsv"
OUT="$ROOT/context/slite"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

[ -f "$LIST" ] || exit 0

# Find the key. Hooks run under bash, which never reads ~/.zshrc, so an export
# that works in your terminal is invisible here. Look in three places, in order:
#   1. the environment
#   2. a dedicated secrets file, chmod 600, outside any synced folder
#   3. the export line in a shell profile, read directly rather than sourced
if [ -z "${SLITE_API_KEY:-}" ] && [ -r "$HOME/.config/slite/api-key" ]; then
  SLITE_API_KEY="$(tr -d '[:space:]' < "$HOME/.config/slite/api-key")"
fi

if [ -z "${SLITE_API_KEY:-}" ]; then
  for profile in "$HOME/.zshenv" "$HOME/.zshrc" "$HOME/.bash_profile" "$HOME/.profile"; do
    [ -r "$profile" ] || continue
    line="$(grep -m1 '^[[:space:]]*export[[:space:]]\+SLITE_API_KEY=' "$profile" 2>/dev/null)" || continue
    [ -n "$line" ] || continue
    # Strip the export keyword, then the surrounding quotes. Never eval the file.
    SLITE_API_KEY="${line#*SLITE_API_KEY=}"
    SLITE_API_KEY="${SLITE_API_KEY%\"}"; SLITE_API_KEY="${SLITE_API_KEY#\"}"
    SLITE_API_KEY="${SLITE_API_KEY%\'}"; SLITE_API_KEY="${SLITE_API_KEY#\'}"
    [ -n "$SLITE_API_KEY" ] && break
  done
fi

if [ -z "${SLITE_API_KEY:-}" ]; then
  echo "slite-pull: SLITE_API_KEY not found, keeping the existing cache" >&2
  exit 0
fi

mkdir -p "$OUT"
pulled=0
failed=0

while IFS=$'\t' read -r note_id filename label; do
  case "$note_id" in ''|'#'*) continue ;; esac

  # One retry. Bursting the whole list at once draws intermittent rate limiting,
  # which showed up as alternating failures on the first run.
  body=""
  for attempt in 1 2; do
    body="$(curl -sS --max-time 15 \
      -H "x-slite-api-key: $SLITE_API_KEY" \
      "https://api.slite.com/v1/notes/${note_id}?format=md" 2>/dev/null)" && [ -n "$body" ] && break
    [ "$attempt" = 1 ] && sleep 2
  done

  if [ -z "$body" ]; then
    failed=$((failed + 1)); continue
  fi

  md="$(printf '%s' "$body" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(1)
c = d.get("content")
if not c:
    sys.exit(1)
print(c)
' 2>/dev/null)" || { failed=$((failed + 1)); continue; }

  {
    printf '<!-- GENERATED by .claude/hooks/slite-pull.sh. Do not edit. -->\n'
    printf '<!-- Source: Slite note %s. Pulled %s. -->\n\n' "$note_id" "$STAMP"
    printf '# %s\n\n' "${label:-$filename}"
    printf '> Authored in Slite, not in this repo. Edit it in Slite: '
    printf 'https://getcami.slite.com/app/docs/%s\n\n' "$note_id"
    printf '%s\n' "$md"
  } > "$OUT/$filename"

  pulled=$((pulled + 1))
done < "$LIST"

{
  printf '<!-- GENERATED. Do not edit. -->\n\n'
  printf '# Slite-authored context\n\n'
  printf 'Pulled %s. %s note(s) loaded' "$STAMP" "$pulled"
  [ "$failed" -gt 0 ] && printf ', %s failed' "$failed"
  printf '.\n\n'
  printf 'These notes are authored in Slite by the wider team. The repo is the\n'
  printf 'source of truth for everything in `context/` and `context/knowledge/`;\n'
  printf 'this folder is the opposite direction, and is regenerated every session.\n\n'
  for f in "$OUT"/*.md; do
    [ "$(basename "$f")" = "INDEX.md" ] && continue
    [ -f "$f" ] && printf -- '- @./%s\n' "$(basename "$f")"
  done
} > "$OUT/INDEX.md"

echo "slite-pull: $pulled pulled, $failed failed" >&2
exit 0
